//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "https://localhost:7139/";
    }

    /**
     * @return OK
     */
    gET(): Promise<string> {
        let url_ = this.baseUrl + "/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGET(_response);
        });
    }

    protected processGET(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : _responseText;
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    eventsLastGET(amount: number): Promise<ActivityEventDto[]> {
        let url_ = this.baseUrl + "/api/events/last/{amount}";
        if (amount === undefined || amount === null)
            throw new globalThis.Error("The parameter 'amount' must be defined.");
        url_ = url_.replace("{amount}", encodeURIComponent("" + amount));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEventsLastGET(_response);
        });
    }

    protected processEventsLastGET(response: Response): Promise<ActivityEventDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ActivityEventDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ActivityEventDto[]>(null as any);
    }

    /**
     * @return OK
     */
    adminWorldDownloadGET(worldId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/admin/world/{worldId}/download";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAdminWorldDownloadGET(_response);
        });
    }

    protected processAdminWorldDownloadGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    authPOST(body: RequestAuthenticationDto): Promise<AuthenticatedDto> {
        let url_ = this.baseUrl + "/api/auth";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAuthPOST(_response);
        });
    }

    protected processAuthPOST(response: Response): Promise<AuthenticatedDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuthenticatedDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AuthenticatedDto>(null as any);
    }

    /**
     * @return OK
     */
    authRefreshPOST(body: RefreshAuthenticationDto): Promise<AuthenticatedDto> {
        let url_ = this.baseUrl + "/api/auth/refresh";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAuthRefreshPOST(_response);
        });
    }

    protected processAuthRefreshPOST(response: Response): Promise<AuthenticatedDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuthenticatedDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AuthenticatedDto>(null as any);
    }

    /**
     * @return OK
     */
    highscoresTrophiesGET(): Promise<HighscoreResponse[]> {
        let url_ = this.baseUrl + "/api/highscores/trophies";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHighscoresTrophiesGET(_response);
        });
    }

    protected processHighscoresTrophiesGET(response: Response): Promise<HighscoreResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HighscoreResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HighscoreResponse[]>(null as any);
    }

    /**
     * @return OK
     */
    highscoresSpeedrunGET(): Promise<HighscoreResponse[]> {
        let url_ = this.baseUrl + "/api/highscores/speedrun";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHighscoresSpeedrunGET(_response);
        });
    }

    protected processHighscoresSpeedrunGET(response: Response): Promise<HighscoreResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HighscoreResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HighscoreResponse[]>(null as any);
    }

    /**
     * @return OK
     */
    highscoresBuilderGET(): Promise<HighscoreResponse[]> {
        let url_ = this.baseUrl + "/api/highscores/builder";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHighscoresBuilderGET(_response);
        });
    }

    protected processHighscoresBuilderGET(response: Response): Promise<HighscoreResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HighscoreResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HighscoreResponse[]>(null as any);
    }

    /**
     * @param id (optional) 
     * @param username (optional) 
     * @return OK
     */
    profileGET(id: string | undefined, username: string | undefined): Promise<FullProfileResponse> {
        let url_ = this.baseUrl + "/api/profile?";
        if (id === null)
            throw new globalThis.Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        if (username === null)
            throw new globalThis.Error("The parameter 'username' cannot be null.");
        else if (username !== undefined)
            url_ += "username=" + encodeURIComponent("" + username) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProfileGET(_response);
        });
    }

    protected processProfileGET(response: Response): Promise<FullProfileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FullProfileResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FullProfileResponse>(null as any);
    }

    /**
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    profileWorldsGET(profileId: string, page: number | undefined, pageSize: number | undefined): Promise<SimpleWorldResponse[]> {
        let url_ = this.baseUrl + "/api/profile/{profileId}/worlds?";
        if (profileId === undefined || profileId === null)
            throw new globalThis.Error("The parameter 'profileId' must be defined.");
        url_ = url_.replace("{profileId}", encodeURIComponent("" + profileId));
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProfileWorldsGET(_response);
        });
    }

    protected processProfileWorldsGET(response: Response): Promise<SimpleWorldResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SimpleWorldResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SimpleWorldResponse[]>(null as any);
    }

    /**
     * @return OK
     */
    sessionUsernamePOST(body: SessionUpdate): Promise<boolean> {
        let url_ = this.baseUrl + "/api/session/username";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSessionUsernamePOST(_response);
        });
    }

    protected processSessionUsernamePOST(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return OK
     */
    worldGET(worldId: string): Promise<FullWorldResponse> {
        let url_ = this.baseUrl + "/api/world/{worldId}";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldGET(_response);
        });
    }

    protected processWorldGET(response: Response): Promise<FullWorldResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FullWorldResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FullWorldResponse>(null as any);
    }

    /**
     * @return OK
     */
    worldMinimapGET(worldId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/world/{worldId}/minimap";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldMinimapGET(_response);
        });
    }

    protected processWorldMinimapGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param page (optional) 
     * @param limit (optional) 
     * @return OK
     */
    worldSpeedrunsGET(worldId: string, page: number | undefined, limit: number | undefined): Promise<WorldSpeedRecordsResponse> {
        let url_ = this.baseUrl + "/api/world/{worldId}/speedruns?";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldSpeedrunsGET(_response);
        });
    }

    protected processWorldSpeedrunsGET(response: Response): Promise<WorldSpeedRecordsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorldSpeedRecordsResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorldSpeedRecordsResponse>(null as any);
    }

    /**
     * @param page (optional) 
     * @param limit (optional) 
     * @return OK
     */
    worldCommentsGET(worldId: string, page: number | undefined, limit: number | undefined): Promise<RealmPlayerComment[]> {
        let url_ = this.baseUrl + "/api/world/{worldId}/comments?";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldCommentsGET(_response);
        });
    }

    protected processWorldCommentsGET(response: Response): Promise<RealmPlayerComment[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RealmPlayerComment.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RealmPlayerComment[]>(null as any);
    }

    /**
     * @return OK
     */
    worldPlayPOST(worldId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/world/{worldId}/play";
        if (worldId === undefined || worldId === null)
            throw new globalThis.Error("The parameter 'worldId' must be defined.");
        url_ = url_.replace("{worldId}", encodeURIComponent("" + worldId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldPlayPOST(_response);
        });
    }

    protected processWorldPlayPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    worldsGET(page: number | undefined, pageSize: number | undefined): Promise<SimpleWorldResponse[]> {
        let url_ = this.baseUrl + "/api/worlds?";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldsGET(_response);
        });
    }

    protected processWorldsGET(response: Response): Promise<SimpleWorldResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SimpleWorldResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SimpleWorldResponse[]>(null as any);
    }

    /**
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    worldsRatedGET(page: number | undefined, pageSize: number | undefined): Promise<SimpleWorldResponse[]> {
        let url_ = this.baseUrl + "/api/worlds/rated?";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldsRatedGET(_response);
        });
    }

    protected processWorldsRatedGET(response: Response): Promise<SimpleWorldResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SimpleWorldResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SimpleWorldResponse[]>(null as any);
    }

    /**
     * @param worldName (optional) 
     * @param builderName (optional) 
     * @param ratedOnly (optional) 
     * @param featuredOnly (optional) 
     * @param rankedOnly (optional) 
     * @param difficulties (optional) 
     * @param contestId (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    worldsSearchGET(worldName: string | undefined, builderName: string | undefined, ratedOnly: boolean | undefined, featuredOnly: boolean | undefined, rankedOnly: boolean | undefined, difficulties: number[] | undefined, contestId: string | undefined, page: number | undefined, pageSize: number | undefined): Promise<SimpleWorldResponse[]> {
        let url_ = this.baseUrl + "/api/worlds/search?";
        if (worldName === null)
            throw new globalThis.Error("The parameter 'worldName' cannot be null.");
        else if (worldName !== undefined)
            url_ += "WorldName=" + encodeURIComponent("" + worldName) + "&";
        if (builderName === null)
            throw new globalThis.Error("The parameter 'builderName' cannot be null.");
        else if (builderName !== undefined)
            url_ += "BuilderName=" + encodeURIComponent("" + builderName) + "&";
        if (ratedOnly === null)
            throw new globalThis.Error("The parameter 'ratedOnly' cannot be null.");
        else if (ratedOnly !== undefined)
            url_ += "RatedOnly=" + encodeURIComponent("" + ratedOnly) + "&";
        if (featuredOnly === null)
            throw new globalThis.Error("The parameter 'featuredOnly' cannot be null.");
        else if (featuredOnly !== undefined)
            url_ += "FeaturedOnly=" + encodeURIComponent("" + featuredOnly) + "&";
        if (rankedOnly === null)
            throw new globalThis.Error("The parameter 'rankedOnly' cannot be null.");
        else if (rankedOnly !== undefined)
            url_ += "RankedOnly=" + encodeURIComponent("" + rankedOnly) + "&";
        if (difficulties === null)
            throw new globalThis.Error("The parameter 'difficulties' cannot be null.");
        else if (difficulties !== undefined)
            difficulties && difficulties.forEach(item => { url_ += "Difficulties=" + encodeURIComponent("" + item) + "&"; });
        if (contestId === null)
            throw new globalThis.Error("The parameter 'contestId' cannot be null.");
        else if (contestId !== undefined)
            url_ += "ContestId=" + encodeURIComponent("" + contestId) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWorldsSearchGET(_response);
        });
    }

    protected processWorldsSearchGET(response: Response): Promise<SimpleWorldResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SimpleWorldResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SimpleWorldResponse[]>(null as any);
    }
}

export class ActivityEventDto implements IActivityEventDto {
    eventType?: string;
    createdAt?: Date;
    extraVariables?: { [key: string]: string; };

    [key: string]: any;

    constructor(data?: IActivityEventDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.eventType = _data["eventType"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            if (_data["extraVariables"]) {
                this.extraVariables = {} as any;
                for (let key in _data["extraVariables"]) {
                    if (_data["extraVariables"].hasOwnProperty(key))
                        (this.extraVariables as any)![key] = _data["extraVariables"][key];
                }
            }
        }
    }

    static fromJS(data: any): ActivityEventDto {
        data = typeof data === 'object' ? data : {};
        let result = new ActivityEventDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["eventType"] = this.eventType;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        if (this.extraVariables) {
            data["extraVariables"] = {};
            for (let key in this.extraVariables) {
                if (this.extraVariables.hasOwnProperty(key))
                    (data["extraVariables"] as any)[key] = (this.extraVariables as any)[key];
            }
        }
        return data;
    }
}

export interface IActivityEventDto {
    eventType?: string;
    createdAt?: Date;
    extraVariables?: { [key: string]: string; };

    [key: string]: any;
}

export class AuthenticatedDto implements IAuthenticatedDto {
    success?: boolean;
    refreshToken?: string;
    jwtToken?: string;

    [key: string]: any;

    constructor(data?: IAuthenticatedDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.success = _data["success"];
            this.refreshToken = _data["refreshToken"];
            this.jwtToken = _data["jwtToken"];
        }
    }

    static fromJS(data: any): AuthenticatedDto {
        data = typeof data === 'object' ? data : {};
        let result = new AuthenticatedDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["success"] = this.success;
        data["refreshToken"] = this.refreshToken;
        data["jwtToken"] = this.jwtToken;
        return data;
    }
}

export interface IAuthenticatedDto {
    success?: boolean;
    refreshToken?: string;
    jwtToken?: string;

    [key: string]: any;
}

export class FullProfileResponse implements IFullProfileResponse {
    id?: string;
    username?: string;
    smiley?: string;
    playerGroup?: number;
    trophies?: number;
    builderPoints?: number;
    verified?: boolean;
    totalPlays!: number;
    completedWorlds!: number;

    [key: string]: any;

    constructor(data?: IFullProfileResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.username = _data["username"];
            this.smiley = _data["smiley"];
            this.playerGroup = _data["playerGroup"];
            this.trophies = _data["trophies"];
            this.builderPoints = _data["builderPoints"];
            this.verified = _data["verified"];
            this.totalPlays = _data["totalPlays"];
            this.completedWorlds = _data["completedWorlds"];
        }
    }

    static fromJS(data: any): FullProfileResponse {
        data = typeof data === 'object' ? data : {};
        let result = new FullProfileResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["username"] = this.username;
        data["smiley"] = this.smiley;
        data["playerGroup"] = this.playerGroup;
        data["trophies"] = this.trophies;
        data["builderPoints"] = this.builderPoints;
        data["verified"] = this.verified;
        data["totalPlays"] = this.totalPlays;
        data["completedWorlds"] = this.completedWorlds;
        return data;
    }
}

export interface IFullProfileResponse {
    id?: string;
    username?: string;
    smiley?: string;
    playerGroup?: number;
    trophies?: number;
    builderPoints?: number;
    verified?: boolean;
    totalPlays: number;
    completedWorlds: number;

    [key: string]: any;
}

export class FullWorldResponse implements IFullWorldResponse {
    description?: string;
    id?: string;
    shortHash?: string;
    title?: string;
    ownerId?: string;
    requestedDifficulty?: number;
    ratedDifficulty?: number | undefined;
    featuredLevel?: number;
    playerDifficulty?: number | undefined;
    plays?: number;
    ranked?: boolean;
    likes!: number;
    ownerUsername!: string;
    completions!: number;
    completed!: boolean;
    secondsToComplete?: number | undefined;

    [key: string]: any;

    constructor(data?: IFullWorldResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.description = _data["description"];
            this.id = _data["id"];
            this.shortHash = _data["shortHash"];
            this.title = _data["title"];
            this.ownerId = _data["ownerId"];
            this.requestedDifficulty = _data["requestedDifficulty"];
            this.ratedDifficulty = _data["ratedDifficulty"];
            this.featuredLevel = _data["featuredLevel"];
            this.playerDifficulty = _data["playerDifficulty"];
            this.plays = _data["plays"];
            this.ranked = _data["ranked"];
            this.likes = _data["likes"];
            this.ownerUsername = _data["ownerUsername"];
            this.completions = _data["completions"];
            this.completed = _data["completed"];
            this.secondsToComplete = _data["secondsToComplete"];
        }
    }

    static fromJS(data: any): FullWorldResponse {
        data = typeof data === 'object' ? data : {};
        let result = new FullWorldResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["description"] = this.description;
        data["id"] = this.id;
        data["shortHash"] = this.shortHash;
        data["title"] = this.title;
        data["ownerId"] = this.ownerId;
        data["requestedDifficulty"] = this.requestedDifficulty;
        data["ratedDifficulty"] = this.ratedDifficulty;
        data["featuredLevel"] = this.featuredLevel;
        data["playerDifficulty"] = this.playerDifficulty;
        data["plays"] = this.plays;
        data["ranked"] = this.ranked;
        data["likes"] = this.likes;
        data["ownerUsername"] = this.ownerUsername;
        data["completions"] = this.completions;
        data["completed"] = this.completed;
        data["secondsToComplete"] = this.secondsToComplete;
        return data;
    }
}

export interface IFullWorldResponse {
    description?: string;
    id?: string;
    shortHash?: string;
    title?: string;
    ownerId?: string;
    requestedDifficulty?: number;
    ratedDifficulty?: number | undefined;
    featuredLevel?: number;
    playerDifficulty?: number | undefined;
    plays?: number;
    ranked?: boolean;
    likes: number;
    ownerUsername: string;
    completions: number;
    completed: boolean;
    secondsToComplete?: number | undefined;

    [key: string]: any;
}

export class HighscoreResponse implements IHighscoreResponse {
    username!: string;
    amount!: number;

    [key: string]: any;

    constructor(data?: IHighscoreResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
            this.amount = _data["amount"];
        }
    }

    static fromJS(data: any): HighscoreResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HighscoreResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        data["amount"] = this.amount;
        return data;
    }
}

export interface IHighscoreResponse {
    username: string;
    amount: number;

    [key: string]: any;
}

export class RealmPlayerComment implements IRealmPlayerComment {
    playerId!: string;
    playerName!: string;
    smiley!: string;
    suggestedRating!: number | undefined;
    liked!: boolean | undefined;
    completed!: boolean;
    completedDeathless!: boolean;

    [key: string]: any;

    constructor(data?: IRealmPlayerComment) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.playerId = _data["playerId"];
            this.playerName = _data["playerName"];
            this.smiley = _data["smiley"];
            this.suggestedRating = _data["suggestedRating"];
            this.liked = _data["liked"];
            this.completed = _data["completed"];
            this.completedDeathless = _data["completedDeathless"];
        }
    }

    static fromJS(data: any): RealmPlayerComment {
        data = typeof data === 'object' ? data : {};
        let result = new RealmPlayerComment();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["playerId"] = this.playerId;
        data["playerName"] = this.playerName;
        data["smiley"] = this.smiley;
        data["suggestedRating"] = this.suggestedRating;
        data["liked"] = this.liked;
        data["completed"] = this.completed;
        data["completedDeathless"] = this.completedDeathless;
        return data;
    }
}

export interface IRealmPlayerComment {
    playerId: string;
    playerName: string;
    smiley: string;
    suggestedRating: number | undefined;
    liked: boolean | undefined;
    completed: boolean;
    completedDeathless: boolean;

    [key: string]: any;
}

export class RefreshAuthenticationDto implements IRefreshAuthenticationDto {
    token?: string;

    [key: string]: any;

    constructor(data?: IRefreshAuthenticationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): RefreshAuthenticationDto {
        data = typeof data === 'object' ? data : {};
        let result = new RefreshAuthenticationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token;
        return data;
    }
}

export interface IRefreshAuthenticationDto {
    token?: string;

    [key: string]: any;
}

export class RequestAuthenticationDto implements IRequestAuthenticationDto {
    code?: string;

    [key: string]: any;

    constructor(data?: IRequestAuthenticationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.code = _data["code"];
        }
    }

    static fromJS(data: any): RequestAuthenticationDto {
        data = typeof data === 'object' ? data : {};
        let result = new RequestAuthenticationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["code"] = this.code;
        return data;
    }
}

export interface IRequestAuthenticationDto {
    code?: string;

    [key: string]: any;
}

export class SessionUpdate implements ISessionUpdate {
    username?: string | undefined;

    [key: string]: any;

    constructor(data?: ISessionUpdate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
        }
    }

    static fromJS(data: any): SessionUpdate {
        data = typeof data === 'object' ? data : {};
        let result = new SessionUpdate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        return data;
    }
}

export interface ISessionUpdate {
    username?: string | undefined;

    [key: string]: any;
}

export class SimpleWorldResponse implements ISimpleWorldResponse {
    id?: string;
    shortHash?: string;
    title?: string;
    ownerId?: string;
    requestedDifficulty?: number;
    ratedDifficulty?: number | undefined;
    featuredLevel?: number;
    playerDifficulty?: number | undefined;
    plays?: number;
    ranked?: boolean;
    likes!: number;
    ownerUsername!: string;
    completions!: number;
    completed!: boolean;
    secondsToComplete!: number | undefined;

    [key: string]: any;

    constructor(data?: ISimpleWorldResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.shortHash = _data["shortHash"];
            this.title = _data["title"];
            this.ownerId = _data["ownerId"];
            this.requestedDifficulty = _data["requestedDifficulty"];
            this.ratedDifficulty = _data["ratedDifficulty"];
            this.featuredLevel = _data["featuredLevel"];
            this.playerDifficulty = _data["playerDifficulty"];
            this.plays = _data["plays"];
            this.ranked = _data["ranked"];
            this.likes = _data["likes"];
            this.ownerUsername = _data["ownerUsername"];
            this.completions = _data["completions"];
            this.completed = _data["completed"];
            this.secondsToComplete = _data["secondsToComplete"];
        }
    }

    static fromJS(data: any): SimpleWorldResponse {
        data = typeof data === 'object' ? data : {};
        let result = new SimpleWorldResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["shortHash"] = this.shortHash;
        data["title"] = this.title;
        data["ownerId"] = this.ownerId;
        data["requestedDifficulty"] = this.requestedDifficulty;
        data["ratedDifficulty"] = this.ratedDifficulty;
        data["featuredLevel"] = this.featuredLevel;
        data["playerDifficulty"] = this.playerDifficulty;
        data["plays"] = this.plays;
        data["ranked"] = this.ranked;
        data["likes"] = this.likes;
        data["ownerUsername"] = this.ownerUsername;
        data["completions"] = this.completions;
        data["completed"] = this.completed;
        data["secondsToComplete"] = this.secondsToComplete;
        return data;
    }
}

export interface ISimpleWorldResponse {
    id?: string;
    shortHash?: string;
    title?: string;
    ownerId?: string;
    requestedDifficulty?: number;
    ratedDifficulty?: number | undefined;
    featuredLevel?: number;
    playerDifficulty?: number | undefined;
    plays?: number;
    ranked?: boolean;
    likes: number;
    ownerUsername: string;
    completions: number;
    completed: boolean;
    secondsToComplete: number | undefined;

    [key: string]: any;
}

export class WorldSpeedRecord implements IWorldSpeedRecord {
    smiley!: string;
    username!: string;
    duration!: string;
    durationAsString?: string | undefined;

    [key: string]: any;

    constructor(data?: IWorldSpeedRecord) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.smiley = _data["smiley"];
            this.username = _data["username"];
            this.duration = _data["duration"];
            this.durationAsString = _data["durationAsString"];
        }
    }

    static fromJS(data: any): WorldSpeedRecord {
        data = typeof data === 'object' ? data : {};
        let result = new WorldSpeedRecord();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["smiley"] = this.smiley;
        data["username"] = this.username;
        data["duration"] = this.duration;
        data["durationAsString"] = this.durationAsString;
        return data;
    }
}

export interface IWorldSpeedRecord {
    smiley: string;
    username: string;
    duration: string;
    durationAsString?: string | undefined;

    [key: string]: any;
}

export class WorldSpeedRecordsResponse implements IWorldSpeedRecordsResponse {
    records!: WorldSpeedRecord[];
    ownRecord!: WorldSpeedRecord | undefined;

    [key: string]: any;

    constructor(data?: IWorldSpeedRecordsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.records = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["records"])) {
                this.records = [] as any;
                for (let item of _data["records"])
                    this.records!.push(WorldSpeedRecord.fromJS(item));
            }
            this.ownRecord = _data["ownRecord"] ? WorldSpeedRecord.fromJS(_data["ownRecord"]) : undefined as any;
        }
    }

    static fromJS(data: any): WorldSpeedRecordsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new WorldSpeedRecordsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.records)) {
            data["records"] = [];
            for (let item of this.records)
                data["records"].push(item ? item.toJSON() : undefined as any);
        }
        data["ownRecord"] = this.ownRecord ? this.ownRecord.toJSON() : undefined as any;
        return data;
    }
}

export interface IWorldSpeedRecordsResponse {
    records: WorldSpeedRecord[];
    ownRecord: WorldSpeedRecord | undefined;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}